baicuoiky/Web/Web/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class TrangChuController : Controller
    {
        //
        // GET: /TrangChu/

        public ActionResult TrangChu()
        {
            return View();
        }
        public ActionResult TCPost()
        {
            return View();
        }
    }
}

baicuoiky/Web/Web/Views/TrangChu/DinhDuong.cshtml
@{
    ViewBag.Title = "Dinh Dưỡng";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}

<h2>DinhDuong</h2>
<fieldset>
    <legend>BaiViet</legend>
    <div id="resuft">
        @*@foreach (var BaiViet in Model.BaiViet.OrderByDescending(x => x.DateCreated).Take(10))
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Body)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Body)
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        }*@
    </div>
</fieldset>

baicuoiky/Web/Web/Views/TrangChu/Index.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/TrangChu/Index.cshtml";
}
@*@Html.ActionLink("Dinh Dưỡng","DinhDuong","TrangChu")*@
            <div class="box-img-pro-home">
            <img src="~/Content/Image/Untitled.png"/>
            </div>

            <h2>
                Khởi đầu vững chắc
                Tiến bước tương lai
            </h2>
            <div class="menu">
                <ul id="nav">
                    <li><a href="Index.cshtml" class="top-link">Trang Chủ</a></li>
                    <li><a href="TrangChu.html" class="top-link">Siêu Thị</a></li>
                    <li><a href="TrangChu.html" class="top-link">Thư Viện</a></li>
                    <li><a href="TrangChu.html" class="top-link">Đăng Bài</a></li>
                </ul>
            </div>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Style.css" rel="stylesheet" />
    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
        </div>
    </header>
    <div class="main">

        @RenderBody()
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>
</body>
</html>

baicuoiky/Web/Web/Views/TrangChu/TCPost.cshtml
@model Web.Models.Post
<div class="display-label">
    @Html.DisplayNameFor(model => model.Title)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Title)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Body)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Body)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.DayCreated)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.DayCreated)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.DateUpdated)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.DateUpdated)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.UserProfile.UserName)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.UserProfile.UserName)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.ChuyenMuc.TenCM)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.ChuyenMuc.TenCM)
</div>

baicuoiky/Web/Web/Views/TrangChu/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}

<h2>TrangChu</h2>
@Html.Partial("TCPost", new Web.Models.Post(),ViewData);